# Generated by Django 5.0.4 on 2024-06-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_flan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='owner',
        ),
        migrations.AlterField(
            model_name='flan',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
